language: csharp
solution: chat-sec-app.sln
install:
  - nuget restore chat-sec-app.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug ./chat.teste/chat.teste.csproj
  - xbuild /p:Configuration=Debug ./chat.dominio/chat.dominio.csproj
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./chat.teste/bin/Debug/chat.teste.dll
notifications:
  slack:
    on_success: always
    on_failure: always 
